name:                ical
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  ical-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ical
