name: ical
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - text
  - validity
  - validity-bytestring
  - validity-text

tests:
  ical-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-sydtest
    - genvalidity-text
    - ical
    - sydtest
