name: ical
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - case-insensitive
  - containers
  - dlist
  - megaparsec
  - network-uri
  - text
  - time
  - validity
  - validity-bytestring
  - validity-case-insensitive
  - validity-containers
  - validity-text
  - validity-time
