name: ical
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - megaparsec
  - text
  - validity
  - validity-bytestring
  - validity-text
