name: ical
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - base64
  - bytestring
  - case-insensitive
  - containers
  - deepseq
  - dlist
  - megaparsec
  - mtl
  - network-uri
  - text
  - time
  - time-compat
  - validity
  - validity-bytestring
  - validity-case-insensitive
  - validity-containers
  - validity-network-uri
  - validity-text
  - validity-time
