name: ical
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - case-insensitive
  - containers
  - dlist
  - megaparsec
  - network-uri
  - text
  - time
  - validity
  - validity-bytestring
  - validity-case-insensitive
  - validity-containers
  - validity-network-uri
  - validity-text
  - validity-time

# For coverage reports, until this issue is fixed:
# https://github.com/commercialhaskell/stack/issues/5713
tests:
  ical-dummy:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ical

