- ignore: { name: "Redundant if" }
- ignore: { name: "Replace case with maybe" }
- ignore: { name: "Avoid lambda using `infix`" }
- ignore: { name: "Use list comprehension" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use newtype instead of data" }
- ignore: { name: "Use ++" }
- ignore: { name: "Use <$>" }
- ignore: { name: "Use unless" }
- ignore: { name: "Fuse mapM/map" }
