resolver: lts-22.22
packages:
- ical
- ical-gen
- ical-recurrence
- ical-recurrence-gen

- ical-interop-test

# These are duplicated in nix/overlay.nix
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages

extra-deps:
- timeout-0.1.1@sha256:56c1d3321d7139d1f7ebf04d46c95d3a3f1c8c9e0f15666ae3ccd6bae6204b6e,1427

- github: NorfairKing/fast-myers-diff
  commit: 5191e044b018224566494465e5f0bea5739a2525
  subdirs:
  - fast-myers-diff
- github: NorfairKing/opt-env-conf
  commit: be38b03718899ee7819054ee442cbb637108201e
  subdirs:
  - opt-env-conf
- github: NorfairKing/conformance
  commit: 27e6479eb7f1cca918f1cef0c122f72e6a5ea026
  subdirs:
  - conformance
  - conformance-gen

- github: NorfairKing/autodocodec
  commit: a7488a3303e06cf06d3d0f2f20203f67fa4500ce
  subdirs:
  - autodocodec
  - autodocodec-nix
  - autodocodec-schema
  - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: 9ed65a40b3b2fade447c9d5fcb941d58f6367308
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: aab13681d89f0875411f2ac2b8d7dd7822869b5f
  subdirs:
  - sydtest
  - sydtest-discover
- github: NorfairKing/validity
  commit: 657cf4bdc2731387abea6e707b88d381d5218616
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-network-uri
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-case-insensitive
  - validity-containers
  - validity-network-uri
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

system-ghc: true
nix:
  enable: false
with-hpack: hpack
