resolver: lts-23.19
packages:
- ical
- ical-gen
- ical-recurrence
- ical-recurrence-gen

- ical-interop-test

# These are duplicated in nix/overlay.nix
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages

extra-deps:
- timeout-0.1.1@sha256:56c1d3321d7139d1f7ebf04d46c95d3a3f1c8c9e0f15666ae3ccd6bae6204b6e,1427
- conformance-gen-0.0.0.0@sha256:7d98b5a0f5b68bb20e13fb7d6830c0e0c59f1778e4d1c74a3075bab0fad47542,978


system-ghc: true
nix:
  enable: false
with-hpack: hpack
