name: ical-gen
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5
- ical

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - case-insensitive
  - containers
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-text
  - text

tests:
  ical-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - dlist
    - genvalidity
    - genvalidity-sydtest
    - ical-gen
    - megaparsec
    - pretty-show
    - sydtest
    - text
