name: ical-gen
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5
- ical

extra-source-files:
- test_resources/**/*

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - bytestring
  - case-insensitive
  - containers
  - dlist
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-network-uri
  - genvalidity-sydtest
  - genvalidity-text
  - genvalidity-time
  - megaparsec
  - network-uri
  - sydtest
  - text
  - time

executables:
  ical-spec-coverage:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - path
    - path-io
    - safe-coloured-text
    - safe-coloured-text-terminfo
    - text
    - vector


benchmarks:
  ical-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - deepseq
    - genvalidity
    - genvalidity-criterion
    - genvalidity-vector
    - ical
    - ical-gen
    - vector

tests:
  ical-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - dlist
    - genvalidity
    - genvalidity-sydtest
    - ical-gen
    - megaparsec
    - network-uri
    - pretty-show
    - sydtest
    - text
    - time
    - validity-network-uri
