name: ical-gen
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5
- ical

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - case-insensitive
  - containers
  - dlist
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-network-uri
  - genvalidity-sydtest
  - genvalidity-text
  - genvalidity-time
  - megaparsec
  - network-uri
  - sydtest
  - text
  - time

tests:
  ical-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - dlist
    - genvalidity
    - genvalidity-sydtest
    - ical-gen
    - megaparsec
    - network-uri
    - pretty-show
    - sydtest
    - text
    - time
    - validity-network-uri

  ical-integration-test:
    main: Spec.hs
    source-dirs: integration-test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - genvalidity-sydtest
    - ical
    - ical-gen
    - path
    - path-io
    - process
    - sydtest
    - text
