{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE ScopedTypeVariables #-}

module ICal.Recurrence.RecurrenceRule
  ( recurRecurrenceRuleDateTimeStarts,
    recurRecurrenceRuleLocalTimes,
  )
where

import Data.Set (Set)
import qualified Data.Set as S
import Data.Time as Time
import ICal.Property
import ICal.PropertyType
import ICal.Recurrence.Class
import ICal.Recurrence.RecurrenceRule.Daily
import ICal.Recurrence.RecurrenceRule.Hourly
import ICal.Recurrence.RecurrenceRule.Minutely
import ICal.Recurrence.RecurrenceRule.Monthly
import ICal.Recurrence.RecurrenceRule.Secondly
import ICal.Recurrence.RecurrenceRule.Weekly
import ICal.Recurrence.RecurrenceRule.Yearly

recurRecurrenceRuleDateTimeStarts ::
  -- | Whether a generated local time exists at all
  (LocalTime -> Bool) ->
  -- | Limit
  Day ->
  DateTimeStart ->
  RecurrenceRule ->
  R (Set DateTimeStart)
recurRecurrenceRuleDateTimeStarts exists limit start recurrenceRule = do
  let localStart = case start of
        DateTimeStartDate (Date d) -> LocalTime d midnight
        DateTimeStartDateTime dt -> case dt of
          DateTimeFloating lt -> lt
          DateTimeUTC ut -> utcToLocalTime utc ut
          DateTimeZoned _ lt -> lt
  localTimes <- recurRecurrenceRuleLocalTimesWhere exists limit localStart recurrenceRule
  pure $
    flip S.map localTimes $ \lt -> case start of
      DateTimeStartDate _ -> DateTimeStartDate $ Date $ localDay lt
      DateTimeStartDateTime dt -> DateTimeStartDateTime $ case dt of
        DateTimeFloating _ -> DateTimeFloating lt
        DateTimeUTC _ -> DateTimeUTC $ localTimeToUTC utc lt
        DateTimeZoned tzid _ -> DateTimeZoned tzid lt

recurRecurrenceRuleLocalTimes ::
  -- | Limit
  Day ->
  -- | DTSTART
  LocalTime ->
  RecurrenceRule ->
  R (Set LocalTime)
recurRecurrenceRuleLocalTimes = recurRecurrenceRuleLocalTimesWhere (const True)

-- | As 'recurRecurrenceRuleLocalTimes', but ignoring the local times that a
-- given predicate rejects
--
-- @
-- Recurrence rules may generate recurrence instances with an invalid
-- date (e.g., February 30) or nonexistent local time (e.g., 1:30 AM
-- on a day where the local time is moved forward by an hour at 1:00
-- AM).  Such recurrence instances MUST be ignored and MUST NOT be
-- counted as part of the recurrence set.
-- @
--
-- @
-- the BYxxx rule parts
-- are applied to the current set of evaluated occurrences in the
-- following order: [...] and BYSETPOS; then COUNT and UNTIL are
-- evaluated.
-- @
--
-- An ignored instance never becomes an occurrence, and COUNT and UNTIL count
-- occurrences and are evaluated last, so the rejected local times have to go
-- before either of them is applied rather than after.  An invalid date is
-- already dropped this early, by the day generation itself, so this keeps the
-- two halves of that requirement behaving the same way.
--
-- The predicate is deliberately not in 'R': keeping it pure is what lets the
-- list stay lazy, so a COUNT still stops as soon as it has enough rather than
-- generating every occurrence up to the limit first.
--
-- DTSTART is not subject to it.  It is not generated by the rule, and it
-- defines the first instance of the recurrence whatever it says.
recurRecurrenceRuleLocalTimesWhere ::
  -- | Whether a generated local time exists at all
  (LocalTime -> Bool) ->
  -- | Limit
  Day ->
  -- | DTSTART
  LocalTime ->
  RecurrenceRule ->
  R (Set LocalTime)
recurRecurrenceRuleLocalTimesWhere exists limit start recurrenceRule =
  S.insert start <$> case recurrenceRuleUntilCount recurrenceRule of
    Nothing -> goIndefinitely
    Just (Left u) -> goUntil u
    Just (Right c) -> goCount c
  where
    localTimes :: R [LocalTime]
    localTimes = filter exists <$> recurrenceRuleDateTimeOccurrences limit start recurrenceRule

    goUntil :: Until -> R (Set LocalTime)
    goUntil u = recurUntil u <$> localTimes
    recurUntil :: Until -> [LocalTime] -> Set LocalTime
    recurUntil _ [] = S.empty
    recurUntil u (l : ls) =
      if l `lessThanUntil` u
        then S.insert l $ recurUntil u ls
        else S.empty

    goCount :: Count -> R (Set LocalTime)
    goCount (Count c) = recurCount (c - 1) <$> localTimes
    recurCount _ [] = S.empty
    recurCount 0 _ = S.empty
    recurCount c (a : as) = S.insert a $ recurCount (pred c) as

    goIndefinitely :: R (Set LocalTime)
    goIndefinitely = S.fromList <$> localTimes

-- TODO: < or <=?
lessThanUntil :: LocalTime -> Until -> Bool
lessThanUntil lt = \case
  UntilDate d -> localDay lt <= unDate d
  UntilDateTimeFloating lt' -> lt <= lt'
  UntilDateTimeUTC ut -> lt <= utcToLocalTime utc ut -- TODO is this correct?!

-- This function takes care of the 'rRuleFrequency' part.
recurrenceRuleDateTimeOccurrences :: Day -> LocalTime -> RecurrenceRule -> R [LocalTime]
recurrenceRuleDateTimeOccurrences limit lt RecurrenceRule {..} = case recurrenceRuleFrequency of
  -- @
  -- The BYDAY rule part MUST NOT be specified with a numeric value when
  -- the FREQ rule part is not set to MONTHLY or YEARLY.  Furthermore,
  -- @
  --
  -- So we 'filterEvery' on the 'byDay's for every frequency except 'MONTHLY' and 'YEARLY'.
  Daily -> do
    every <- filterEvery recurrenceRuleByDay
    pure $
      dailyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleByMonthDay
        every
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos
  Weekly -> do
    every <- filterEvery recurrenceRuleByDay
    pure $
      weeklyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleWeekStart
        every
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos
  Monthly ->
    pure $
      monthlyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleByMonthDay
        recurrenceRuleByDay
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos
  Yearly ->
    pure $
      yearlyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleWeekStart
        recurrenceRuleByWeekNo
        recurrenceRuleByYearDay
        recurrenceRuleByMonthDay
        recurrenceRuleByDay
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos
  Hourly -> do
    every <- filterEvery recurrenceRuleByDay
    pure $
      hourlyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleByYearDay
        recurrenceRuleByMonthDay
        every
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos
  Minutely -> do
    every <- filterEvery recurrenceRuleByDay
    pure $
      minutelyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleByYearDay
        recurrenceRuleByMonthDay
        every
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos
  Secondly -> do
    every <- filterEvery recurrenceRuleByDay
    pure $
      secondlyDateTimeRecurrence
        limit
        lt
        recurrenceRuleInterval
        recurrenceRuleByMonth
        recurrenceRuleByYearDay
        recurrenceRuleByMonthDay
        every
        recurrenceRuleByHour
        recurrenceRuleByMinute
        recurrenceRuleBySecond
        recurrenceRuleBySetPos

-- | Discard the number from a numeric 'ByDay', keeping the week day
--
-- @
-- If an integer
-- modifier is not present, it means all days of this type within the
-- specified frequency.  For example, within a MONTHLY rule, MO
-- represents all Mondays within the month.  The BYDAY rule part MUST
-- NOT be specified with a numeric value when the FREQ rule part is
-- not set to MONTHLY or YEARLY.
-- @
--
-- So the number is forbidden here, and the spec does not say what to do with
-- one anyway.  The quote settles which repair changes the least: the
-- unnumbered form already means every day of that type within the frequency,
-- so keeping the week day and discarding only the number says what the rule
-- nearly said.  'byEveryWeekDayWeek' repairs the same shape the same way.
--
-- Discarding the whole rule part instead would leave the day filter empty,
-- and an empty day filter is no restriction at all, so forbidden input would
-- widen the recurrence set rather than narrow it.
filterEvery :: Set ByDay -> R (Set DayOfWeek)
filterEvery =
  fmap S.fromList
    . mapM
      ( \case
          Every d -> pure d
          bd@(Specific _ d) -> do
            emitFixableErrorR $ RecurrenceByDayNumeric bd
            pure d
      )
    . S.toList
