name: ical-interop-test
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library: {}

tests:
  ical-interop-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - genvalidity-sydtest
    - ical
    - ical-gen
    - path
    - path-io
    - process
    - sydtest
    - text
    - timeout
