name: ical-recurrence-gen
version: 0.0.0.0

extra-source-files:
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5
- containers
- ical
- ical-gen
- ical-recurrence

library:
  source-dirs: src
  dependencies:
  - genvalidity
  - genvalidity-containers

tests:
  ical-recurrence-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity-sydtest
    - genvalidity-time
    - ical-recurrence-gen
    - path
    - path-io
    - sydtest
    - text
    - time
