name: ical-recurrence-gen
version: 0.0.0.0

extra-source-files:
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - genvalidity
  - genvalidity-containers
  - ical-gen
  - ical-recurrence

tests:
  ical-recurrence-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity-sydtest
    - genvalidity-time
    - ical
    - ical-gen
    - ical-recurrence
    - ical-recurrence-gen
    - path
    - path-io
    - sydtest
    - text
    - time
